<?php


namespace App\Controller;


use App\Entity\Articles;
use App\Form\AdminArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("admin/articles", name="article_index")
     */
    public function indexArticles()
    {
        $doctrine = $this->getDoctrine();

        $articleRepository = $doctrine->getRepository(Articles::class);
        $resultatedit= $articleRepository->findAll();

        return $this->render('admin/index_article.html.twig',
            ['resultatedit' => $resultatedit ]);
    }

    /**
     * @Route("admin/addArticle", name="article_add")
     */
    public function adminAddArticle(Request $request)
    {
        $article = new Articles();
        $user = $this->getUser()->getId();
        $form = $this->createForm(AdminArticleType::Class, $article, []);
        $form->handleRequest($request);

        if( $form->isSubmitted() && !$form->isEmpty() && $form->isValid())
        {
            if($article->getImagePrincipale() != '' || $article->getImagePrincipale() != null ){
                //ajout d'une photo
                $file = $form->get('imagePrincipale')->getData();
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('article_pictures_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Un problème est survenue sur la photo de l\'article lors de l\'enregistrement!');

                    return $this->redirectToRoute('article_add', []);
                }
            }
            else{
                $fileName = '';
            }

            $article->setImagePrincipale($fileName);
            $article->setDatePublication(new \DateTime()) ;
            $article->setIdUtilisateur($user);
            $doctrine = $this->getDoctrine();
            $entityManager = $doctrine->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            $this->addFlash('success', 'l\'article a bien été enregistré et publié!');

            return $this->redirectToRoute('home',[]);

        }
        return $this->render('admin/article_admin_add.html.twig',[
            'formAjoutarticle' => $form->createView(),
        ]);
    }


    /**
     * @Route("article/{id}", name="article")
     */
    public function readArticle(Articles $id)
    {
        $doctrine = $this->getDoctrine();
        $userRepository = $doctrine->getRepository(Articles::class);
        $resultatArticle= $userRepository->find($id);

        return $this->render('home/article.html.twig', [
            'resultatArticle' => $resultatArticle,
        ]);
    }


    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}